[project]
name = "td-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=0.186.1",
    "crewai-tools>=0.76.0",
    "fastmcp>=2.14.1",
    "mysql-connector-python>=9.5.0",
    "nest-asyncio>=1.6.0",
    "python-dotenv>=1.1.1",
    "python-telegram-bot>=21.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
bot = "td_chat.telegram_bot:main"
run = "td_chat.telegram_bot:main"
train = "td_chat.main:train"
replay = "td_chat.main:replay"
test = "td_chat.main:test"
