[project]
name = "td_chat"
version = "0.1.0"
description = "td-chat using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = "~3.12"
dependencies = [
    "crewai[tools]>=0.177.0,<1.0.0",
    "fastapi>=0.111.0,<1.0.0",
    "uvicorn[standard]>=0.29.0,<1.0.0",
    "python-dotenv>=1.0.0",
    "mysql-connector-python>=8.0.0",
    "python-telegram-bot==21.2"
]

[tool.poetry.scripts]
run = "td_chat.main:run"
train = "td_chat.main:train"
replay = "td_chat.main:replay"
test = "td_chat.main:test"
serve = "uvicorn.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"

[tool.poetry]
name = "td_chat"
version = "0.1.0"
description = "td-chat using crewAI"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "td_chat", from = "src"}]
